train_config:
  epochs: 120
  batch_size: 32
  force_retrain: True
  model_name: "hopper_bc_baseline"
  optimizers:
    0:
      lr: 0.001
      weight_decay: 0.00001

model_config:
  type: "mlp"
  scale: True
  obs_horizon: 1
  act_horizon: 1
  hidden_dims:
  - 128
  - 128
  - 128
  dropout_rate: 0.0
  batch_norm: True
  assume_io_size: True
  optimizer: 0

# Expected score: 2313.65
