model_config:
  act_horizon: 1
  assume_io_size: true
  batch_norm: true
  darp: true
  dropout_rate: 0.0
  hidden_dims:
  - 128
  - 128
  - 128
  obs_horizon: 1
  optimizer: 0
  retrieval_config:
    decay_rate: -0.7359995486097888
    final_neighbors_ratio: 0.593485269170173
    k: 246
    lookback: 13
    method: knn
  scale: true
  type: mlp
train_config:
  batch_size: 32
  force_retrain: True
  epochs: 237
  model_name: hopper_darp_baseline
  optimizers:
    0:
      lr: 0.001
      weight_decay: 0.00001

# Expected score: 3545.57