demo_pkl: "data/threading_task_D0/100_r3m_full.pkl"
prop_demo_pkl: "data/threading_task_D0/100_proprio.pkl"
act_demo_pkl: "data/threading_task_D0/100_actions.pkl"
type: 'r3m'
demo_hdf5: "data/threading_task_D0/demo.hdf5"
robosuite: True
add_proprio: True
name: Threading_D0
cams:
  - agentview
  - robot0_eye_in_hand
