name: nearest-sequence
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pip=22.0.2
  - numpy=1.26.4
  - Cython=0.29.32
  - setuptools=65.5.0
  - wheel=0.38.4
  - cmake=3.30.5
  # These are for mujoco-py, not necessary if you have sudo on your machine and can install without conda
  - glew
  - mesalib
  - patchelf

  - pip:
    - torch==2.4.1
    - torchvision==0.19.1
    - gym==0.19.0
    - diffusers==0.30.0
    - PyYAML==6.0.1
    - d4rl==1.1
    - tensorboard==2.19.0
    - scipy==1.11.4
    - git+https://github.com/aravindr93/mjrl@3871d93763d3b49c4741e6daeaebbc605fe140dc
    # Just for Push T
    - pygame==2.5.0
    - pymunk==6.2.1
    - Shapely==1.8.4
    - opencv-python==4.10.0.84
