model_config:
  act_horizon: 1
  assume_io_size: true
  batch_norm: true
  darp: true
  dropout_rate: 0.0
  hidden_dims:
  - 256
  - 256
  - 256
  obs_horizon: 1
  optimizer: 0
  retrieval_config:
    decay_rate: -0.5256205418343101
    final_neighbors_ratio: 0.1296895441599067
    k: 1916
    lookback: 44
    method: knn
  scale: true
  type: mlp
train_config:
  batch_size: 32
  force_retrain: True
  epochs: 113
  model_name: square_darp_baseline
  optimizers:
    0:
      lr: 0.01
      weight_decay: 0.000001

# Expected score: 0.62
