train_config:
  epochs: 190
  batch_size: 32
  cond_force_retrain: True
  model_name: "walker_bc_baseline"
  optimizers:
    0:
      lr: 0.01
      weight_decay: 0.000001

model_config:
  type: "mlp"
  scale: True
  obs_horizon: 1
  act_horizon: 1
  hidden_dims:
  - 256
  - 256
  - 256
  dropout_rate: 0.0
  batch_norm: True
  assume_io_size: True
  optimizer: 0

#load_resnet: False
# (13:04:47 train_bc.py@679 INFO) Evaluating epoch 190...
# (13:04:53 train_bc.py@699 INFO) New best score 2658.398506003721 found at epoch 190

