model_config:
  demo_pkl: data/stack_task_D0/100_proprio_r3m.pkl
  r3m_config:
    input_len: 768
    rgb_height: 224
    rgb_width: 224
    scale: false
    type: identity
  fusion_config:
    batch_norm: false
    demo_pkl: data/stack_task_D0/100_proprio_r3m.pkl
    dropout_rate: 0.0
    hidden_dims:
    - 1024
    - 512
    - 512
    optimizer: 0
    output_len: 7
    scale: true
    scale_input: false
    type: mlp
  prop_config:
    demo_pkl: data/stack_task_D0/100_proprio.pkl
    input_len: 9
    scale: true
    scale_output: false
    type: identity
  tune: false
  type: r3m_fusion
train_config:
  batch_size: 32
  epochs: 245
  force_retrain: true
  model_name: bc_img
  optimizers:
    0:
      lr: 0.001
      weight_decay: 0.0001

# (00:55:02 train_bc.py@700 INFO) New best score 0.17 found at epoch 245
