cond_force_retrain: true
model_config:
  act_config:
    demo_pkl: data/stack_task_D0/100_actions.pkl
    input_len: 7
    scale: true
    scale_output: false
    type: identity
  darp: true
  demo_pkl: data/stack_task_D0/100_r3m_full.pkl
  fusion_config:
    batch_norm: false
    demo_pkl: data/stack_task_D0/100_r3m_full.pkl
    dropout_rate: 0.0
    hidden_dims:
    - 1024
    - 512
    - 512
    optimizer: 0
    output_len: 7
    scale: true
    scale_input: false
    type: mlp
  prop_config:
    batch_norm: false
    demo_pkl: data/stack_task_D0/100_proprio.pkl
    input_len: 9
    optimizer: 1
    scale: true
    scale_output: false
    type: identity
  r3m_config:
    input_len: 512
    rgb_height: 224
    rgb_width: 224
    scale: false
    type: identity
  retrieval_config:
    decay_rate: -0.5075966299905339
    final_neighbors_ratio: 0.38094660733665014
    k: 174
    lookback: 34
    method: knn
  sideload_r3m: true
  tune: false
  type: r3m_darp
train_config:
  batch_size: 32
  epochs: 34
  force_retrain: true
  model_name: r3m_darp
  optimizers:
    0:
      lr: 1e-3
      weight_decay: 1e-5

# (00:34:34 study.py@1163 INFO) Trial 64 finished with value: 0.52 and parameters: {'epochs': 34, 'k': 174, 'lookback': 34, 'decay_rate': -0.5075966299905339, 'final_neighbors_ratio': 0.38094660733665014}. Best is trial 64 with value: 0.52.

