train_config:
  epochs: 5
  batch_size: 32
  cond_force_retrain: True
  model_name: "bc_close_door_baseline"
  optimizers:
    0:
      lr: 0.01
      weight_decay: 0.000001

model_config:
  type: "mlp"
  scale: True
  obs_horizon: 1
  act_horizon: 1
  hidden_dims:
  - 256
  - 256
  - 256
  dropout_rate: 0.0
  batch_norm: True
  assume_io_size: True
  optimizer: 0

#(22:53:45 train_bc.py@1004 INFO) New best score 0.29 found at epoch 5

