model_config:
  act_horizon: 1
  assume_io_size: true
  batch_norm: true
  darp: true
  dropout_rate: 0.0
  hidden_dims:
  - 256
  - 256
  - 256
  obs_horizon: 1
  optimizer: 0
  retrieval_config:
    decay_rate: -2.421120881367398
    final_neighbors_ratio: 0.15203398111888175
    k: 93
    lookback: 34
    method: knn
  scale: true
  type: mlp
train_config:
  batch_size: 32
  force_retrain: True
  epochs: 294
  model_name: ant_darp_baseline
  optimizers:
    0:
      lr: 0.01
      weight_decay: 0.000001

# Expected score: 4383.28

